add flacky zsh func helper

diff --git a/dot_config/zsh/functions/basic b/dot_config/zsh/functions/basic
--- a/dot_config/zsh/functions/basic
+++ b/dot_config/zsh/functions/basic
@@ -129,3 +129,26 @@ function vmrss() {
     done
     printf "Total: $total MB\n"
 }
+
+
+function flacky() {
+  command=$1
+  if [ -z "$command" ]; then
+    echo "flacky() - run command until it fails"
+    echo "Usage: flacky <command>"
+    return
+  fi
+  while true; do
+    # Run the command, capturing both stdout and stderr.
+    output=$(bash -c "$command" 2>&1)
+    exit_code=$?
+    if [ $exit_code -ne 0 ]; then
+        echo "Command failed with exit code: $exit_code"
+        echo "Output of the failed execution:"
+        echo "$output"
+        exit $exit_code
+    fi
+
+    echo "Command succeeded, running again..."
+done
+}
